##06/15/2013
## simulation codes for large etwork 


####
## generate netowork: "dense_p500_adj_matrix.Rdata": large network, generated by "generate_network_05132012.txt"
## the latter code also plot the network 
> Plot_XYZ(result.xyz,hub.size=10, lay=layout.fruchterman.reingold)



#### generate data 
####"data_generation_05132012" codes to generate data 
## parameter to change when generating data: sample size n (100, 250)
## SNR: 0.5~1.5: min=0.5, max=1.5; 0.2~0.5: min=0.2, max=0.5

### notes: "network_gene_function_10172012.txt" with sign flip 


### run methods 
######### run array job by Gauss 
## "dense_p500_n250_bagshuffle.R": run methods and summarize results 
## "dense_p500_n250_bagshuffle.sh"
## notes: when make changes, use an editor under unix (for format)

## score comparison
"gic_bagging_shuffling_large_n100.txt"

## covariance estimation
"para_estimation_dense_p500_n100_indep100_0515_05252013.txt" 